//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DjSoft.Games.Animated.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DjSoft.Games.Sudoku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua00 {
            get {
                object obj = ResourceManager.GetObject("Aqua00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua01 {
            get {
                object obj = ResourceManager.GetObject("Aqua01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua02 {
            get {
                object obj = ResourceManager.GetObject("Aqua02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua03 {
            get {
                object obj = ResourceManager.GetObject("Aqua03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua04 {
            get {
                object obj = ResourceManager.GetObject("Aqua04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua05 {
            get {
                object obj = ResourceManager.GetObject("Aqua05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua06 {
            get {
                object obj = ResourceManager.GetObject("Aqua06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua07 {
            get {
                object obj = ResourceManager.GetObject("Aqua07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua08 {
            get {
                object obj = ResourceManager.GetObject("Aqua08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua09 {
            get {
                object obj = ResourceManager.GetObject("Aqua09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua10 {
            get {
                object obj = ResourceManager.GetObject("Aqua10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua11 {
            get {
                object obj = ResourceManager.GetObject("Aqua11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua12 {
            get {
                object obj = ResourceManager.GetObject("Aqua12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua41 {
            get {
                object obj = ResourceManager.GetObject("Aqua41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua42 {
            get {
                object obj = ResourceManager.GetObject("Aqua42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua43 {
            get {
                object obj = ResourceManager.GetObject("Aqua43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua44 {
            get {
                object obj = ResourceManager.GetObject("Aqua44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua45 {
            get {
                object obj = ResourceManager.GetObject("Aqua45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua46 {
            get {
                object obj = ResourceManager.GetObject("Aqua46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua47 {
            get {
                object obj = ResourceManager.GetObject("Aqua47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua48 {
            get {
                object obj = ResourceManager.GetObject("Aqua48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqua49 {
            get {
                object obj = ResourceManager.GetObject("Aqua49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGAxialis_IconWorkshop {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGAxialis_IconWorkshop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGCDRWin {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGCDRWin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGChange_User {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGChange_User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGClock {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGCPU_Usage {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGCPU_Usage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGDVD2AVI {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGDVD2AVI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGKKMenu_Audio {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGKKMenu_Audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGKKMenu_Office {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGKKMenu_Office", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGKKMenu_Windows {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGKKMenu_Windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGLogof_Logon {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGLogof_Logon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Authorware {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Authorware", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_ColdFusion_MX {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_ColdFusion_MX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Contribute {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Contribute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Director_MX {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Director_MX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Dreamweaver_MX {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Dreamweaver_MX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Extension_Manager {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Extension_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Flash_MX {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Flash_MX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Homesite {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Homesite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_JRun_MX {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_JRun_MX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMacromedia_Shockwave {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMacromedia_Shockwave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMicrosoft_Visual_Studio_C__ {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMicrosoft_Visual_Studio_C__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMicrosoft_Windows_System_Manager {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMicrosoft_Windows_System_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGMoby_Dock {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGMoby_Dock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGRestart {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGRestart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGShutdown_Quit_Dock {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGShutdown_Quit_Dock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGStandby {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGStandby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGStardock_CursorXP {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGStardock_CursorXP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGSyncronize__Universal_ {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGSyncronize__Universal_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gloss_PNGWinRar {
            get {
                object obj = ResourceManager.GetObject("Gloss_PNGWinRar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_aria_enterprise128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_aria_enterprise128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_authorware128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_authorware128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_authorware128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_authorware128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_breeze_document64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_breeze_document64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_breeze128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_breeze128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_central128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_central128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_central2004_look128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_central2004_look128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_coldfusion_mx_doc64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_coldfusion_mx_doc64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_coldfusion_mx128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_coldfusion_mx128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_coldfusion_new_doc64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_coldfusion_new_doc64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_coldfusion_new128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_coldfusion_new128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_contribute128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_contribute128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_contribute2004_look128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_contribute2004_look128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_course_builder128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_course_builder128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_director128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_director128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_director8_128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_director8_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_dream_weaver_doc64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_dream_weaver_doc64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_dream_weaver_ultradev128x12 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_dream_weaver_ultradev128x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_dream_weaver128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_dream_weaver128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_dream_weaver4_128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_dream_weaver4_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_dreamweaver_ultra_128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_dreamweaver_ultra_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_dreamweaver2004_128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_dreamweaver2004_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_extension_manager128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_extension_manager128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_fireworks_doc64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_fireworks_doc64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_fireworks128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_fireworks128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_fireworks2004_128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_fireworks2004_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_fireworks4_128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_fireworks4_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_fireworks4_yellow128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_fireworks4_yellow128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_communication_server9 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_communication_server9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_enebled128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_enebled128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_metalic_doc64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_metalic_doc64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_metalic128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_metalic128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_red_document_fla64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_red_document_fla64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_red_document64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_red_document64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_red128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_red128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash_remoting128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash_remoting128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash2004_128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash2004_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flash5_128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flash5_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_flex128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_flex128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_freehand_128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_freehand_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_freehand_doc64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_freehand_doc64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_freehand10_128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_freehand10_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_freehand10_doc64x64 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_freehand10_doc64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_generator128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_generator128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_homesite128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_homesite128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_jrun128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_jrun128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_like_minds128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_like_minds128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_macromedia128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_macromedia128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_shockwave128x128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_shockwave128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_studioMX1_128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_studioMX1_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macromedia_luiscds_studioMX2_128 {
            get {
                object obj = ResourceManager.GetObject("macromedia_luiscds_studioMX2_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
